language: generic

services:
  - docker

cache:
  directories:
    - "$HOME/.m2"

before_install:
  - docker pull maven:3-jdk-8

script:
  - docker run -v ${HOME}/.m2:/root/.m2 -v ${PWD}:${PWD} -i -t maven:3-jdk-8 /bin/bash -c "mvn -f ${PWD} clean verify"

before_cache:
  - rm -Rf $HOME/.m2/repository/org/apache/beam/samples
  - find $HOME/.m2/repository/ -name *SNAPSHOT | xargs rm -Rf
