name: Java CI
on:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # Once per day at midnight
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        BEAM_VERSION:
          - 2.19.0
          - 2.21.0-SNAPSHOT
      fail-fast: false
    steps:
      - name: Checkout jbonofre/beam-samples
        uses: actions/checkout@v2
      - name: Cache maven artifacts
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run build
        run:
          mvn clean verify -Pbeam-release-repo -D"beam.version"="${{ matrix.BEAM_VERSION }}"
