name: Java CI
on:
  push:
  schedule:
    - cron: '0 0 * * *' # Once per day at midnight
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BEAM_VERSION:
          - 2.19.0
          - 2.20.0-SNAPSHOT
      fail-fast: false
    steps:
      - name: Checkout jbonofre/beam-samples
        uses: actions/checkout@v2
      - name: Run build
        run:
          mvn clean verify -Pbeam-release-repo -Dbeam.version=${{ matrix.BEAM_VERSION }}
