name: Java 8
on:
  push:
  pull_request:
  schedule:
    # Once a day from monday to friday after the daily SNAPSHOTS are published
    - cron: '0 10 * * 1-5'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        BEAM_VERSION:
          - 2.40.0
          - 2.41.0-SNAPSHOT
        SPARK3_VERSION:
          - 3.0.2
          - 3.1.2
      fail-fast: false
    steps:
      - name: Checkout Talend/beam-samples
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Cache maven artifacts
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and Run Tests
        run:
          mvn clean verify -D"beam.version"="${{ matrix.BEAM_VERSION }}"
      # Run some samples
      - name: Run Avro SQL Pipeline - Direct Runner
        run:
          mvn -pl sql exec:java -D"exec.mainClass"="org.apache.beam.samples.sql.BeamSqlAvroExample" -Pdirect-runner -D"exec.args"="--runner=DirectRunner"
      # Run some samples in linux only for more complex open source runners
      #- name: Run Avro SQL Pipeline - Spark Classic Runner (Spark 2)
      #  if: matrix.os == 'ubuntu-latest'
      #  run:
      #    mvn -pl sql exec:java -Dexec.mainClass=org.apache.beam.samples.sql.BeamSqlAvroExample -Pspark-runner -Dexec.args="--runner=SparkRunner"
      - name: Run Avro SQL Pipeline - Spark Classic Runner (Spark 3) "${{ matrix.SPARK3_VERSION }}"
        if: matrix.os == 'ubuntu-latest'
        run:
          mvn -pl sql exec:java -Dexec.mainClass=org.apache.beam.samples.sql.BeamSqlAvroExample -Pspark3-runner -D"spark3.version"="${{ matrix.SPARK3_VERSION }}" -Dexec.args="--runner=SparkRunner"
      #- name: Run Avro SQL Pipeline - Spark Structured Streaming Runner (Spark 2)
      #  if: matrix.os == 'ubuntu-latest'
      #  run:
      #    mvn -pl sql exec:java -Dexec.mainClass=org.apache.beam.samples.sql.BeamSqlAvroExample -Pspark-runner -Dexec.args="--runner=SparkStructuredStreamingRunner"
      - name: Run Avro SQL Pipeline - Flink Runner
        if: matrix.os == 'ubuntu-latest'
        run:
          mvn -pl sql exec:java -Dexec.mainClass=org.apache.beam.samples.sql.BeamSqlAvroExample -Pflink-runner -Dexec.args="--runner=FlinkRunner"
